import Head from 'next/head'
import { useState } from "react";
import {BsFillMoonStarsFill, BsGithub, BsLinkedin} from 'react-icons/bs';
import Image from 'next/image';

import avatarHalf from '../public/avatar-half.png';

import design from '../public/design.png';
import code from '../public/code.png';

import web1 from '../public/web1.gif';
import web2 from '../public/web2.gif';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Harshada Gundecha Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className='min-h-screen '>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='font-Alegreya text-xl '>H.G.Portfolio</h1>
            <ul className='flex items-center'>
              <li>
              <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-cyan-600 text-white px-4 py-2 rounded-md ml-9' href="https://drive.google.com/file/d/1PVm4wdlyc1yPB8pSH5WlueX-p0Fmi0mT/view?usp=sharing">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium font-Alegreya dark:text-teal-400'>Harshada Gundecha</h2>
            <h3 className='text-2xl py-2 dark:text-white font-Roboto-Mono'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 font-Roboto-Mono'>
              Building the web one page at a time! <br />
              Join me on my journey as I experiment with web design and development.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-200'>
           <a href="https://github.com/HarshadaG06"><BsGithub/></a>
           <a href="https://www.linkedin.com/in/harshada-gundecha2000/"><BsLinkedin/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-cyan-600 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={avatarHalf} alt="Avatar Wave" layout='fill' className='m-auto'/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 font-Roboto-Mono font-medium dark:text-white'>My Skillset :</h3>
            <p className='text-md py-2 leading-8 text-gray-800 font-Roboto-Monofont-medium dark:text-gray-200'>
            - Hands on experience with <span className='text-cyan-600 dark:text-cyan-300'>Java backend development</span> and web development using <span className='text-cyan-600 dark:text-cyan-300'>HTML, JavaScript, CSS</span> in my current job role as <span className='text-cyan-600 dark:text-cyan-300'>Junior Engineer at Cornerstone OnDemand.</span> <br />
            - Experience building user interfaces with <span className='text-cyan-600 dark:text-cyan-300'>Figma</span>, good understanding of UI principles and hands on experience building web projects using <span className='text-cyan-600 dark:text-cyan-300'> React.js</span>. <br />
            - Good understanding of <span className='text-cyan-600 dark:text-cyan-300'> Data structures and Algorithms</span>.<br />
            - Experience with unit testing and good understanding of CI/CD tools and processes (<span className='text-cyan-600 dark:text-cyan-300'>Bitbucket, GitHub</span>). <br />
            - Good understanding of the <span className='text-cyan-600 dark:text-cyan-300'>Object Oriented Programming</span> Paradigm. <br />
            - Solid grasp of development principles,Database Management Systems(<span className='text-cyan-600 dark:text-cyan-300'>Oracle SQL and MySQL</span>), enterprise design patterns and industry best practices. <br />
            - Well cultivated logical, debugging and reasoning skills. <br />
            </p>
          </div>
          <div className="lg:flex gap-10 justify-around">
            <div className='text-center shadow-lg p-10 rounded-xl dark:bg-gray-100 my-10 '>
              <Image src={design} width={100} height={100}  className='m-auto'alt='Design.png'/>
              <h3 className='text-lg font-medium pt-8 pb-2 font-Roboto-Mono'>Beautiful Designs</h3>
              <p>Creating elegant designs following core design theory</p>
              <h4 className='py-4 text-cyan-600 dark:text-cyan-700 font-Roboto-Mono'>Design tools I use :</h4>
              <p className='text-gray-800 py-1 font-Alegreya'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl dark:bg-gray-100 my-10'>
              <Image src={code} width={100} height={100} className='m-auto ' alt='Code.png'/>
             <h3 className='text-lg font-medium pt-8 pb-2 font-Roboto-Mono'>Bringing designs to life</h3>
              <p>Creating websites that are simple, elegant and accessible.</p>
              <h4 className='py-4 text-cyan-600 dark:text-cyan-700  font-Roboto-Mono'>Web Technologies that I use:</h4>
              <p className='text-gray-800 py-1 font-Roboto-Mono'>React.js</p>
              <p className='text-gray-800 py-1 font-Roboto-Mono'>Node.js</p>
              <p className='text-gray-800 py-1 font-Roboto-Mono'>Redux</p>
              <p className='text-gray-800 py-1 font-Roboto-Mono'>Next.js</p>
              <p className='text-gray-800 py-1 font-Roboto-Mono'>Tailwindcss</p>
            </div>
        </div>
        </section>
        <section className='py-10'>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-200 font-Roboto-Mono text-center '>Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-Roboto-Mono dark:text-gray-200 text-center ">
              Here are a few projects that I have worked on:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <h4 className=' text-center py-4 text-cyan-700 dark:text-cyan-300 font-Roboto-Mono font-medium'>Task Tracker</h4>
              <p className=" text-center text-md py-2 leading-8 text-gray-800 dark:text-gray-400 font-Roboto-Mono">
                View the full project here: <a className='text-cyan-600 dark:text-cyan-200 ' href="https://harshadag06.github.io/todo-app/">TaskTracker</a> <br />
                Check out the code : <a className='text-cyan-600 dark:text-cyan-200' href="https://github.com/HarshadaG06/todo-app">TaskTracker Github</a>
              </p>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt='Task-Tracker'
              />
            </div>
            <div className="basis-1/3 flex-1">
              <h4 className='text-center py-4 text-cyan-700 dark:text-cyan-300 font-Roboto-Mono font-medium'>LinkedIn Clone</h4>
              <p className="text-center text-md py-2 leading-8 text-gray-800 dark:text-gray-400 font-Roboto-Mono">
                View the full project here: <a className='text-cyan-600 dark:text-cyan-200' href="https://linkedin-clone-caa13.web.app/">LinkedIn Clone</a> <br />
                Check out the code : <a className='text-cyan-600 dark:text-cyan-200' href="https://github.com/HarshadaG06/linkedin-clone-yt">LinkedIn Clone Github</a>
              </p>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt='LinkedIn-clone'
              />
            </div>
          </div>
        </section>
      </main>
      </div>
  )
}
